config/routes.rb
Sisdun::Application.routes.draw do
  get "store/index"
  resources :categories
  resources :products
  resources :companies
  resources :customers
  resources :users
  resources :debts do
    resources :partials
    collection { post :search, to: 'debts#index' }
  end
  resources :orders do
    collection { post :search, to: 'orders#index' }
  end
  resources :line_items
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/cities_by_state', to: 'companies#cities_by_state', via: 'get'
  match '/cities_by_state', to: 'customers#cities_by_state', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name, presence: true, 
                   length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { in: 6..20 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :show]
  before_filter :correct_user, only: [:edit, :update, :show]
  before_filter :admin_user, only: [:destroy, :new, :create, :index]

  def index
    @users = User.all
    @users = User.order(params[:sort]) if params[:sort]
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url }
        flash[:success] = "Usuário #{@user.name} criado com sucesso."
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url }
        flash[:success] = "Usuário #{@user.name} atualizado com sucesso."
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      flash[:success] = "Usuário #{@user.name} removido com sucesso."
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
        redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end

    def admin_user
      redirect_to(root_url) unless current_user && current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>  
  <fieldset>
  <legend>Dados do Usuário</legend>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="control-group">
    <%= f.label :name, 'Nome*', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, class: 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, 'E-mail*', class: 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, class: 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, 'Senha*', class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, class: 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, 'Confirmar senha*', class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, class: 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Enviar", class: 'btn btn-primary' %>
    <%= link_to "Cancelar", user_path(@user), class: 'btn' %>
  </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editar Usuário") %>

<div class="page-header">
  <h1>Editar profile</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'Usuários') %>

<div class="page-header">
  <h1>Usuários</h1>
</div>

<table class="table table-striped">
    <thead>
        <tr>
          <th><%= link_to "Id", users_path(sort: "id")%></th>
          <th><%= link_to "Usuário", users_path(sort: "name")%></th>
          <th><%= link_to "E-mail", users_path(sort: "email")%></th>
          <th><%= link_to "Criado em", users_path(sort: "created_at")%></th>
          <th>Ações</th>
        </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.id, user_path(user) %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.strftime('%d/%m/%Y')  %></td>
          <td>
            <%= link_to "Mostrar", user, class: 'btn btn-mini' %>
            <% if current_user.admin? && !current_user?(user) %>
              <%= link_to "Editar", edit_user_path(user), class: 'btn btn-mini' %>
              <%= link_to "Deletar", user, method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-mini btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

<%= link_to "Novo", new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<% provide(:title, 'Novo usuário') %>

<div class="page-header">
  <h1>Novo usuário</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="page-header">
  <h1>Usuário: <small><%= @user.name %></small></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nome:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong>E-mail:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Voltar', users_path, class: 'btn' %>
  <% if current_user.admin? && !current_user?(@user) %>
    <%= link_to 'Editar', edit_user_path(@user), class: 'btn' %>
    <%= link_to 'Deletar', @user, method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-danger" %>
  <% end %>
</div>