config/routes.rb
Sisdun::Application.routes.draw do
  get "store/index"
  resources :categories
  resources :products
  resources :companies
  resources :customers
  resources :users
  resources :debts do
    resources :partials
    collection { post :search, to: 'debts#index' }
  end
  resources :orders do
    collection { post :search, to: 'orders#index' }
  end
  resources :line_items
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/cities_by_state', to: 'companies#cities_by_state', via: 'get'
  match '/cities_by_state', to: 'customers#cities_by_state', via: 'get'

end

app/models/company.rb
class CnpjValidator < ActiveModel::EachValidator
  def is_cnpj?(value)
    match = value.gsub(/\D/, "").scan(/\d/).collect(&:to_i)

    if match.size == 14
      match = match.collect{|x| x.to_i}
      sum = match[0] * 5 + match[1] * 4 + match[2] * 3 + match[3] * 2 + match[4] * 9 + match[5] * 8 + match[6] * 7 + match[7] * 6 + match[8] * 5 + match[9] * 4 + match[10] * 3 + match[11] * 2
      sum = sum - (11 * (sum / 11))
      m = (sum == 0 || sum == 1) ? 0 : 11 - sum

      if m == match[12]
        sum = match[0] * 6 + match[1] * 5 + match[2] * 4 + match[3] * 3 + match[4] * 2 + match[5] * 9 + match[6] * 8 + match[7] * 7 + match[8] * 6 + match[9] * 5 + match[10] * 4 + match[11] * 3 + match[12] * 2
        sum = sum - (11 * (sum / 11))
        n = (sum == 0 || sum == 1) ? 0 : 11 - sum

        return n == match[13]
      end
    end

   false
  end

  def validate_each(record, attribute, value)
    unless is_cnpj?(value)
      message = I18n.translate("errors.messages.invalid")
      record.errors[attribute] << message
    end
  end
end

class Company < ActiveRecord::Base
  has_one :address, :as => :addressable, :dependent => :destroy
  has_one :contact, :as => :contactable, :dependent => :destroy
  accepts_nested_attributes_for :address, :contact
  validates :company_name, presence: true,
                           uniqueness: true
  VALID_CNPJ_REGEX = /\d{2}\.\d{3}\.\d{3}\/\d{4}\-\d{2}/
  validates :cnpj, presence: true,
                   uniqueness: true,
                   format: { with: VALID_CNPJ_REGEX },
                   exclusion: { in: %w(11.111.111/1111-11 22.222.222/2222-22 33.333.333/3333-33 44.444.444/4444-44 55.555.555/5555-55 66.666.666/6666-66 77.777.777/7777-77 88.888.888/8888-88 99.999.999/9999-99 00.000.000/0000-00) },
                   cnpj: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :signed_in_user
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  # GET /companies
  # GET /companies.json
  def index
    @search = Company.search(params[:q])
    @companies = @search.result
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.build_address
    @company.build_contact
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company } 
        flash[:success] = "Empresa #{@company.company_name} criada com sucesso."
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company } 
        flash[:success] = "Empresa #{@company.company_name} criada com sucesso."
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      flash[:success] = "Empresa #{@company.company_name} removida com sucesso."
      format.json { head :no_content }
    end
  end

  def cities_by_state
    state_id = params[:id].to_i
    cities = City.where(:state_id => state_id)
    cty = []
    cities.each do |city|
      cty << {:id => city.id, :n => city.name}
    end
    render :json => {:cty => cty.compact}.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :trading_name, :cnpj, address_attributes:[:line1, :line2, :number, :postal_code, :city_id], contact_attributes:[:phone1, :phone2, :phone3, :email])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <fieldset>
    <legend>Dados da Empresa</legend>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="control-group">
      <%= f.label :company_name, 'Razão Social*', class: 'control-label' %>
      <div class="controls"> 
        <%= f.text_field :company_name, class: 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :trading_name, 'Nome Fantasia', class: 'control-label' %>
      <div class="controls"> 
        <%= f.text_field :trading_name, class: 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :cnpj, 'CNPJ*', class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :cnpj, id: 'cnpj', class: 'text_field' %>
      </div>
    </div>
  </fieldset>
  <fieldset>
    <legend>Endereço</legend>
    <%= f.fields_for :address do |address| %>
      <div class="control-group">
        <%= address.label :line1, "Endereço*", class: 'control-label' %>
        <div class="controls">
          <%= address.text_field :line1, class: 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= address.label :line2, "Complemento*", class: 'control-label' %>
        <div class="controls">
          <%= address.text_field :line2, class: 'text_field'  %>
        </div>
      </div>
      <div class="control-group">
        <%= address.label :number, "Numero*", class: 'control-label' %>
        <div class="controls">
          <%= address.text_field :number, class: 'text_field'  %>
        </div>
      </div>
      <div class="control-group">
        <%= address.label :postal_code, "CEP*", class: 'control-label' %>
        <div class="controls">
          <%= address.text_field :postal_code, id: 'cep', class: 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= address.label :State, "Estado*", class: 'control-label' %>
        <div class="controls">
          <%= collection_select(:state ,:id, State.all, :id, :name, :include_blank => 'Estados') %>
        </div>
      </div>
      <div class="control-group">
        <%= address.label :City, "Cidade*", class: 'control-label' %>
        <div class="controls">
          <%= address.collection_select :city_id, [], :id, :name, :include_blank => 'Selecione um estado' %>
        </div>
      </div>
    <% end %>
  </fieldset>
  <fieldset>
    <legend>Contato</legend>
    <%= f.fields_for :contact do |contact| %>
      <div class="control-group">
        <%= contact.label :phone1, "Telefone Principal*", class: 'control-label' %>
        <div class="controls">
          <%= contact.text_field :phone1, id: 'phone1', class: 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :phone2, "Telefone Celular", class: 'control-label' %>
        <div class="controls">
          <%= contact.text_field :phone2, id: 'phone2', class: 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :phone3, "Telefone Comercial", class: 'control-label' %>
        <div class="controls">
          <%= contact.text_field :phone3, id: 'phone3', class: 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :email, "E-mail", class: 'control-label' %>
        <div class="controls">
          <%= contact.email_field :email, class: 'text_field' %>
        </div>
      </div>
    <% end %>
  </fieldset>
  <div class="form-actions">
    <%= f.submit "Enviar", class: 'btn btn-primary' %>
    <%= link_to "Cancelar", company_path(@company), class: 'btn' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% provide(:title, "Editar Empresa") %>

<h1>Editar Empresa</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<% provide(:title, 'Empresas') %>

<div class="page-header">
  <h1>Empresas</h1>
</div>

<div class="control-groups">
  <%= search_form_for @search do |f| %>
    <div class="input-append">
      <%= f.label :company_name_cont, "Razão Social", class: "input-medium search-query" %>
      <%= f.text_field :company_name_cont %>
      <button class="btn"><% f.submit %>Pesquisar</button>
    </div>
  <% end %>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Razão Social</th>
      <th>Nome Fantasia</th>
      <th>CNPJ</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to(company.id, company) %></td>
        <td><%= company.company_name %></td>
        <td><%= company.trading_name %></td>
        <td><%= company.cnpj %></td>
        <td>
            <%= link_to "Mostrar", company, class: 'btn btn-mini' %>
            <%= link_to "Editar", edit_company_path(company), class: 'btn btn-mini' %>
            <%= link_to "Deletar", company, method: :delete, data: { confirm: "Você tem certeza?"}, class: "btn btn-mini btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Novo", new_company_path, class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<% provide(:title, 'Nova Empresa') %>

<div class="page-header">
  <h1>Nova Empresa</h1>
</div>

<%= render 'form' %>

app/views/companies/show.html.erb
<% provide(:title, @company.company_name) %>

<div class="page-header">
  <h1>Empresa: <small><%= @company.company_name %></small></h1>
</div>

<dl class="dl-horizontal">
  <fieldset>
    <legend>Dados empresa:</legend>
    <dt><strong>Id:</strong></dt>
    <dd><%= @company.id %></dd>
    <dt><strong>Razão Social:</strong></dt>
    <dd><%= @company.company_name %></dd>
    <dt><strong>Nome Fantasia:</strong></dt>
    <dd><%= nil?(@company.trading_name) %></dd>
    <dt><strong>Cnpj:</strong></dt>
    <dd><%= @company.cnpj %></dd>
  </fieldset>
  </br>
  <fieldset>
    <legend>Endereço:</legend>
    <dt><strong>Cidade:</strong></dt>
    <dd><%= @company.address.city.name+", "+@company.address.city.state.abbreviation %></dd>
    <dt><strong>Endereço:</strong></dt>
    <dd><%= @company.address.line1 %></dd>
    <dt><strong>Complemento:</strong></dt>
    <dd><%= @company.address.line2 %></dd>
    <dt><strong>Numero:</strong></dt>
    <dd><%= @company.address.number %></dd>
    <dt><strong>CEP:</strong></dt>
    <dd><%= @company.address.postal_code %></dd>
  </fieldset>
  </br>
  <fieldset>
    <legend>Contato:</legend>
    <dt><strong>Telefone Principal:</strong></dt>
    <dd><%= @company.contact.phone1 %></dd>
    <dt><strong>Telefone Celular:</strong></dt>
    <dd><%= nil?(@company.contact.phone2) %></dd>
    <dt><strong>Telefone Comercial:</strong></dt>
    <dd><%= nil?(@company.contact.phone3) %></dd>
    <dt><strong>E-mail:</strong></dt>
    <dd><%= nil?(@company.contact.email) %></dd>
  </fieldset>
  </br>
</dl>

<div class="form-actions">
    <%= link_to 'Voltar', companies_path, class: 'btn' %>
    <%= link_to "Editar", edit_company_path(@company), class: 'btn' %>
    <%= link_to "Deletar", @company, method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-danger" %>
</div>