config/routes.rb
Sisdun::Application.routes.draw do
  get "store/index"
  resources :categories
  resources :products
  resources :companies
  resources :customers
  resources :users
  resources :debts do
    resources :partials
    collection { post :search, to: 'debts#index' }
  end
  resources :orders do
    collection { post :search, to: 'orders#index' }
  end
  resources :line_items
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/cities_by_state', to: 'companies#cities_by_state', via: 'get'
  match '/cities_by_state', to: 'customers#cities_by_state', via: 'get'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :signed_in_user
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Tentativa de acessar carrinho invalido #{params[:id]}"
      redirect_to store_index_url, notice: 'Carrinho invalido'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2>Carrinho</h2>
<table>

<%= render(cart.line_items) %>

<tr class="total_line">
<td colspan="2"><strong>Total</strong></td>
<td class="total_cell"><strong>
  <%= sprintf("%0.2f",cart.total_price) %></strong></td>
</tr>
</table>

</br>
<%= button_to 'Limpar Carrinho', cart, method: :delete,
data: { confirm: 'Voce tem certeza?' } %>
<%= button_to "Efetuar Venda", new_order_path, method: :get, class: 'btn btn-primary'%>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/old.show.html.erb
<% provide(:title, 'Carrinho') %>

<div class="page-header">
  <h1>Lista de itens</h1>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Produto</th>
      <th>Preço</th>
      <th></th>
      <th>Quantidade</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.line_items.each do |item| %>
      <tr>
        <td><%= item.product.category.name %></td>
        <td><%= item.product.title %></td>
        <td><%= number_to_currency(item.product.price) %></td>
        <td>&times;</td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.total_price) %></td>
        
      </tr>
    <% end %>

    <tr>
      <td colspan="5" class=""><strong>Total</strong></td>
      <td class="total_cell"><strong><%= number_to_currency(@cart.total_price) %></strong></td>
    </tr>
  </tbody>
</table>

<%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/carts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<%= render @cart %>