config/routes.rb
Sisdun::Application.routes.draw do
  get "store/index"
  resources :categories
  resources :products
  resources :companies
  resources :customers
  resources :users
  resources :debts do
    resources :partials
    collection { post :search, to: 'debts#index' }
  end
  resources :orders do
    collection { post :search, to: 'orders#index' }
  end
  resources :line_items
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/cities_by_state', to: 'companies#cities_by_state', via: 'get'
  match '/cities_by_state', to: 'customers#cities_by_state', via: 'get'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, presence: true
  validates :price, presence: true,
                    numericality: {greater_than_or_equal_to: 0.01}
  validates :category_id, presence: true

  def self.latest
    Product.order(:updated_at).last
  end

  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Presente em itens do carrinho')
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :signed_in_user
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @search = Product.search(params[:q])
    @products = @search.result
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url }
        flash[:success] = "Produto #{@product.title} criado com sucesso."
        format.json { render action: 'index', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url }
        flash[:success] = "Produto #{@product.title} atualizado com sucesso."
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      flash[:success] = "Produto #{@product.title} removido com sucesso."
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :sale_type, :price, :stock, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <fieldset>
    <legend>Dados do Produtos</legend>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="control-group">
      <%= f.label :title, "Titulo*", class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, class: 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, "Descrição", class: 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, class: 'text_area' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :category_id, "Categorias*", class: 'control-label' %>
      <div class="controls">
        <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => 'Selecione uma categoria' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :price, "Preço*", class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :price, id: 'price', class: 'text_field' %>
      </div>
    </div>
  </fieldset>
  <div class="form-actions">
    <%= f.submit 'Enviar', class: 'btn btn-primary' %>
    <%= link_to 'Cancelar', product_path(@product), class: 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:title, "Editar Produto") %>

<h1>Editar Produto</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<% provide(:title, 'Produtos')%>
<div class="page-header">
  <h1>Produtos</h1>
</div>

<div class="control-groups">
  <%= search_form_for @search do |f| %>
    <div class="input-append">
      <%= f.label :title_cont, "Titulo", class: "input-medium search-query" %>
      <%= f.text_field :title_cont %>
      <button class="btn"><% f.submit %>Pesquisar</button>
    </div>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Titulo</th>
      <th>Categoria</th>
      <th>Descrição</th>
      <th>Preço</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to(product.id, product) %></td>
        <td><%= product.title %></td>
        <th><%= product.category.name %></th>
        <td><%= product.description %></td>
        <td><%= sprintf("%0.2f", product.price) %></td>
        <td>
          <%= link_to 'Mostrar', product, class: 'btn btn-mini' %>
          <%= link_to 'Editar', edit_product_path(product), class: 'btn btn-mini' %>
          <%= link_to 'Deletar', product, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo', new_product_path, class: 'btn btn-primary' %>

app/views/products/new.html.erb
<% provide(:title, 'Novo Produto') %>

<div class="page-header">
  <h1>Novo Produto</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<% provide(:title, @product.title) %>

<div class="page-header">
  <h1>Produto: <small><%= @product.title %></small></h1>
</div>

<dl class="dl-horizontal">
  <fieldset>
    <legend>Dados do Produto</legend>
    <dt><strong>Produto:</strong></dt>
    <dd><%= @product.title %></dd>
    <dt><strong>Descrição:</strong></dt>
    <dd><%= nil?(@product.description) %></dd>
    <dt><strong>Categoria:</strong></dt>
    <dd><%= @product.category.name %></dd>
    <dt><strong>Preço:</strong></dt>
    <dd><%= sprintf("%0.2f", @product.price) %></dd>
  </fieldset>
  </br>
</dl>

<div class="form-actions">
    <%= link_to 'Voltar', products_path, class: 'btn' %>
    <%= link_to "Editar", edit_product_path(@product), class: 'btn' %>
    <%= link_to "Deletar", @product, method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-danger" %>
</div>